coverage:
  range: 30..70 # coverage lower than 30 is red, higher than 70 green, between color code
  status:
    patch: off
  notify:
    after_n_builds: 10000 # stacks-core-tests.yml & bitcoin-test.yml as a minimum
comment: false
