coverage:
  range: "80...100"
  notify:
    require_ci_to_pass: yes
    after_n_builds: 250
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch: off
comment: false
github_checks:
  annotations: false
# coverage:
#   status:
#     patch: off
#   notify:
#     after_n_builds: 10000
# comment: false
# github_checks:
#   annotations: false
