codecov:
  notify:
    require_ci_to_pass: yes
    after_n_builds: 10000

coverage:
  round: up
  precision: 2
  range: "30...100"

  status:
    changes: no
    patch: yes #off
    project: no

comment:
  after_n_builds: 10
# comment: false
