# https://docs.codecov.com/docs/codecovyml-reference
codecov:
  require_ci_to_pass: false # don't require ci to succeed to pass
  notify:
    wait_for_ci: true # wait for all ci jobs to finish before reporting status
coverage:
  range: 60..79 # < 60=red, 60<>80 = yellow, > 80 = green
  round: down # round range down
  precision: 2
  status:
    changes: false
    patch: false
    project: false # this is required if we want to require codecov as a status check
    #  default:
    #    target: 80% # the required coverage value
    #    threshold: 1% # the leniency in hitting the target
# comment: false
comment:
  # layout: "condensed_header, condensed_files, condensed_footer" # add "condensed_" to "header", "files" and "footer"
  layout: "condensed_header, diff, files, footer" # remove "new" from "header" and "footer"
  hide_project_coverage: false # set to true
  after_n_builds: 35 # total number of uploads
github_checks:
  annotations: false # don't annotate on github PR

## during tests, if codecov is a status check it will show as "red" while reports are uploaded (once it passes 80% covered, it is green)
## PR comment will not be uploaded until all CI has completed or at least 35 reports are uploaded
##  the 35 reports seems inaccurate, but using the actual number of 58 causes the comment to not happen 38 also works, and 35 reports the comment at the same time. it's a black box.

