coverage:
  require_ci_to_pass: yes
  range: "80...100"
  notify:
    after_n_builds: 10
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch: off
comment:
  after_n_builds: 10
github_checks:
  annotations: false
