codecov:
  require_ci_to_pass: true
  notify:
    # after_n_builds: 250
    wait_for_ci: true
coverage:
  range: 60..80
  round: down
  precision: 2
  status:
    changes: false
    patch: false
    project:
      default:
        target: 80% # the required coverage value
        threshold: 1% # the leniency in hitting the target
comment: false
github_checks:
  annotations: false
