##
## Build the Docker Debian image from source
##

name: Build Linux Source Image

# Only run when:
#   - workflow is manually triggered
# #   - manually triggered via the ci.yml workflow
#   - PR created, ignoring yaml and markdownfiles

on:
  workflow_dispatch:
  workflow_call:
    # secrets:
    #   DOCKERHUB_USERNAME:
    #     required: true
    #   DOCKERHUB_PASSWORD:
    #     required: true

defaults:
  run:
    shell: bash

env:
  docker_platforms: linux/amd64
  os_version: debian

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "image"
