## Github workflow to run atlas tests

name: Tests::Atlas

on:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15
  RETRIES: 3
  RETRY_DELAY: 10000
  # RUSTFLAGS: "-Cinstrument-coverage -Awarnings"
  # LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
  # BTC_VERSION: "0.20.0"

concurrency:
  group: atlas-tests-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # atlas integration tests with code coverage
  atlas-tests:
    name: Atlas Test
    runs-on: ubuntu-latest
    ## continue tests even if we have a failure
    continue-on-error: true
    ## run a maximum of 2 concurrent tests from the test matrix
    strategy:
      ## continue with the matrix even if we've had a failure
      fail-fast: false
      max-parallel: 2
      matrix:
        test-name:
          - tests::neon_integrations::atlas_integration_test
          - tests::neon_integrations::atlas_stress_integration_test
    steps:
      ## Setup test environment
      - name:  Setup Test Environment
        id: setup_tests
        uses: wileyj/actions/stacks-blockchain/testenv@main

      ## Run test matrix using cached archive file
      ##   - timeout after 30 minutes
      - name: Run Tests
        id: run_tests
        timeout-minutes: 30
        run: |
          cargo nextest run \
            --test-threads num-cpus \
            --run-ignored all \
            --retries 2 \
            --final-status-level fail \
            --fail-fast \
            --archive-file /tmp/test_archive.tar.zst \
            "${{ matrix.test-name }}"

      ## Create and upload code coverage
      - name: Code Coverage
        id: codecov
        uses: wileyj/actions/codecov@main
        with:
          test-name: ${{ matrix.test-name }}
