## Github workflow to run atlas tests

name: Tests::Atlas

on:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15
  RETRIES: 3
  RETRY_DELAY: 10000

concurrency:
  group: atlas-tests-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # atlas integration tests with code coverage
  atlas-tests:
    name: Atlas Test
    runs-on: ubuntu-latest
    ## continue tests even if we have a failure
    continue-on-error: true
    ## run a maximum of 2 concurrent tests from the test matrix
    strategy:
      ## continue with the matrix even if we've had a failure
      fail-fast: false
      max-parallel: 2
      matrix:
        test-name:
          - tests::neon_integrations::atlas_integration_test
          - tests::neon_integrations::atlas_stress_integration_test
    steps:
      ## Setup test environment
      - name:  Setup Test Environment
        id: setup_tests
        uses: wileyj/actions/stacks-blockchain/testenv@main

      ## Run test matrix using cached archive file
      ##   - timeout after 30 minutes
      - name: Run Tests
        id: run_tests
        timeout-minutes: 30
        run: |
          cargo nextest run \
            --test-threads num-cpus \
            --run-ignored all \
            --retries 2 \
            --final-status-level fail \
            --fail-fast \
            --archive-file /tmp/test_archive.tar.zst \
            "${{ matrix.test-name }}"

      ## grcov
      - name: Code Coverage
        id: codecov
        uses: wileyj/actions/codecov@main
        with:
          test-name: ${{ matrix.test-name }}
          
      # ## Generate code coverage using grcov
      # - name: Run grcov
      #   id: run_grcov
      #   run: |
      #     grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info || exit 1
      #     echo "created=true\n" >> $GITHUB_OUTPUT

      # ## Upload coverage to codecov
      # ##   - use wretry action, to retry on a failed upload
      # - name: Upload Code Coverage
      #   id: code_coverage
      #   uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
      #   # uses: wileyj/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
      #   with:
      #     action: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
      #     with: |
      #       files: ./lcov.info
      #       name: ${{ matrix.test-name }}
      #       fail_ci_if_error: false
      #       verbose: true
      #     attempt_limit: ${{ env.RETRIES}}
      #     attempt_delay: ${{ env.RETRY_DELAY}}
