##
## Performs an audit for crate advisories against cargo dependencies
##

name: Crate Audit

# Only run when:
#   - workflow is manually triggered
#   - Cargo.toml/lock is changed
# Note: this will create issues for any crate advisories unless they already exist

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - "**/Cargo.toml"
  #     - "**/Cargo.lock"

jobs:
  security_audit:
    if: ${{ false }}
    name: Crate Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3

      # - name: Rust Dependency Check
      #   id: rust_dep_check
      #   uses: actions-rs/audit-check@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      - uses: rustsec/audit-check@v1.4.1
        id: rust_audit
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
