## Github workflow to run bitcoin tests

name: Tests::Bitcoin

on:
  workflow_call:

## env vars are transferred to composite action steps
env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15
  TEST_TIMEOUT: 30

concurrency:
  group: bitcoin-tests-${{ github.head_ref || github.ref || github.run_id}}
  ## Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Bitcoin integration tests with code coverage
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      ## Continue with the test matrix even if we've had a failure
      fail-fast: false
      ## Run a maximum of 32 concurrent tests from the test matrix
      max-parallel: 32
      matrix:
        test-name:
          - tests::bitcoin_regtest::bitcoind_integration_test
          - tests::integrations::integration_test_get_info
          - tests::neon_integrations::antientropy_integration_test 
          - tests::neon_integrations::bad_microblock_pubkey
          - tests::neon_integrations::bitcoind_forking_test
          - tests::neon_integrations::bitcoind_integration_test
          - tests::neon_integrations::block_large_tx_integration_test
          - tests::neon_integrations::block_limit_hit_integration_test
          - tests::neon_integrations::cost_voting_integration
          - tests::neon_integrations::filter_long_runtime_tx_integration_test
          - tests::neon_integrations::filter_low_fee_tx_integration_test
          - tests::neon_integrations::fuzzed_median_fee_rate_estimation_test_window10
          - tests::neon_integrations::fuzzed_median_fee_rate_estimation_test_window5
          - tests::neon_integrations::liquid_ustx_integration
          - tests::neon_integrations::microblock_fork_poison_integration_test
          - tests::neon_integrations::microblock_integration_test
          - tests::neon_integrations::microblock_large_tx_integration_test_FLAKY
          - tests::neon_integrations::microblock_limit_hit_integration_test
          - tests::neon_integrations::miner_submit_twice
          - tests::neon_integrations::mining_events_integration_test
          - tests::neon_integrations::pox_integration_test
          - tests::neon_integrations::push_boot_receipts
          - tests::neon_integrations::runtime_overflow_unconfirmed_microblocks_integration_test
          - tests::neon_integrations::should_fix_2771
          - tests::neon_integrations::size_check_integration_test
          - tests::neon_integrations::size_overflow_unconfirmed_invalid_stream_microblocks_integration_test
          - tests::neon_integrations::size_overflow_unconfirmed_microblocks_integration_test
          - tests::neon_integrations::size_overflow_unconfirmed_stream_microblocks_integration_test
          - tests::neon_integrations::stx_delegate_btc_integration_test
          - tests::neon_integrations::stx_transfer_btc_integration_test
          - tests::neon_integrations::test_chainwork_first_intervals
          - tests::neon_integrations::test_chainwork_partial_interval
          - tests::neon_integrations::test_flash_block_skip_tenure
          - tests::neon_integrations::test_problematic_blocks_are_not_mined
          - tests::neon_integrations::test_problematic_blocks_are_not_relayed_or_stored
          - tests::neon_integrations::test_problematic_microblocks_are_not_mined
          - tests::neon_integrations::test_problematic_microblocks_are_not_relayed_or_stored
          - tests::neon_integrations::test_problematic_txs_are_not_stored
          - tests::neon_integrations::use_latest_tip_integration_test
          - tests::neon_integrations::confirm_unparsed_ongoing_ops
          - tests::neon_integrations::min_txs
          - tests::should_succeed_handling_malformed_and_valid_txs
          - tests::nakamoto_integrations::simple_neon_integration
          - tests::nakamoto_integrations::mine_multiple_per_tenure_integration
          - tests::nakamoto_integrations::block_proposal_api_endpoint
          - tests::nakamoto_integrations::miner_writes_proposed_block_to_stackerdb
          - tests::nakamoto_integrations::correct_burn_outs
          - tests::signer::stackerdb_dkg
          - tests::signer::stackerdb_sign
          - tests::signer::stackerdb_block_proposal
          - tests::signer::stackerdb_filter_bad_transactions
          - tests::signer::stackerdb_mine_2_nakamoto_reward_cycles
    steps:
      ## Setup test environment
      - name: Setup Test Environment
        id: setup_tests
        uses: stacks-network/actions/stacks-core/testenv@main
        with:
          btc-version: "25.0"
          
      ## Run test matrix using restored cache of archive file
      ##   - Test will timeout after env.TEST_TIMEOUT minutes
      - name: Run Tests
        id: run_tests
        timeout-minutes: ${{ fromJSON(env.TEST_TIMEOUT) }}
        uses: stacks-network/actions/stacks-core/run-tests@main
        with:
          test-name: ${{ matrix.test-name }}
          threads: 1

      ## Create and upload code coverage file
      - name: Code Coverage
        id: codecov
        uses: stacks-network/actions/codecov@main
        with:
          test-name: ${{ matrix.test-name }}
