##
## Bitcoin Integration Tests
##

name: Bitcoin Integration Tests

on:
  ## run when create-cache has completed successfully
  ##  create-cache will run when an input-tag is provided, or a PR is approved
  # workflow_dispatch:
  workflow_call:
  # workflow_run:
  #   workflows: ["Create Test Caches"]
  #   types:
  #     - completed
  # ## old
  # ## run when tagging a release or a PR is approved
  # workflow_dispatch:
  # # workflow_call:
  # # pull_request_target:
  # #   paths:
  # #     - "**.rs"
  # #     - "**.clar"
  # # pull_request_target:
  # #   # Ignore if a commit only includes changes to a Markdown file.
  # #   paths-ignore:
  # #     - "**/*.md"
  # # push:
  # #   paths-ignore:
  # #     - "*.md"
  # #   tags:
  # #     - "[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+" # 2.1.0.0.0
  # #     - "[0-9]+.[0-9]+.[0-9].[0-9]+.[0-9]+-rc[0-9]+" # 2.1.0.0.0-rc1
  # # pull_request_review:
  # #   types: [submitted]
  # workflow_run:
  #   workflows: ["Create Test Caches"]
  #   types:
  #     - completed

defaults:
  run:
    shell: bash

env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 20

concurrency:
  # group: bitcoin-integration-tests-${{ github.ref }}
  group: bitcoin-tests-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # # check to see if cache exists, if not then recreate it
  # create-cache:
  #   name: Create Test Cache
  #   uses: ./.github/workflows/create-cache.yml
  #   # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  check-cache:
    # if: ${{ false }}
    name: Check Cache
    runs-on: ubuntu-latest
    steps:
      - name: Check Bitcoin Cache
        # uses: buildjet/cache@v3
        uses: actions/cache@v3
        id: check_cache
        with:
          lookup-only: true
          path: /tmp/bitcoin
          key: ${{ github.event.repository.name }}-bitcoin-binaries

      - name: Check Target Cache
        # uses: buildjet/cache@v3
        uses: actions/cache@v3
        id: check_target_cache
        with:
          lookup-only: true
          # path: ./target/debug
          # key: ${{ github.event.repository.name }}-target-debug
          # # key: ${{ github.event.repository.name }}-${{ github.sha }}-target-debug
          path: ./target
          key: ${{ github.event.repository.name }}-target

  # bitcoin integration tests with code coverage
  integration-tests:
    # if: ${{ false }}
    name: Integration Tests
    runs-on: ubuntu-latest
    needs:
      - check-cache
    strategy:
      fail-fast: false
      max-parallel: 32
      matrix:
        test-name:
          - tests::bitcoin_regtest::bitcoind_integration_test
          - tests::integrations::integration_test_get_info
          - tests::neon_integrations::antientropy_integration_test
          - tests::neon_integrations::bad_microblock_pubkey
          - tests::neon_integrations::bitcoind_forking_test
          - tests::neon_integrations::bitcoind_integration_test
          - tests::neon_integrations::block_large_tx_integration_test
          - tests::neon_integrations::block_limit_hit_integration_test
          - tests::neon_integrations::cost_voting_integration
          - tests::neon_integrations::filter_long_runtime_tx_integration_test
          - tests::neon_integrations::filter_low_fee_tx_integration_test
          - tests::neon_integrations::fuzzed_median_fee_rate_estimation_test_window10
          - tests::neon_integrations::fuzzed_median_fee_rate_estimation_test_window5
          - tests::neon_integrations::liquid_ustx_integration
          - tests::neon_integrations::microblock_fork_poison_integration_test
          - tests::neon_integrations::microblock_integration_test
          - tests::neon_integrations::microblock_large_tx_integration_test_FLAKY
          - tests::neon_integrations::microblock_limit_hit_integration_test
          - tests::neon_integrations::miner_submit_twice
          - tests::neon_integrations::mining_events_integration_test
          - tests::neon_integrations::pox_integration_test
          - tests::neon_integrations::push_boot_receipts
          - tests::neon_integrations::runtime_overflow_unconfirmed_microblocks_integration_test
          - tests::neon_integrations::should_fix_2771
          - tests::neon_integrations::size_check_integration_test
          - tests::neon_integrations::size_overflow_unconfirmed_invalid_stream_microblocks_integration_test
          - tests::neon_integrations::size_overflow_unconfirmed_microblocks_integration_test
          - tests::neon_integrations::size_overflow_unconfirmed_stream_microblocks_integration_test
          - tests::neon_integrations::stx_delegate_btc_integration_test
          - tests::neon_integrations::stx_transfer_btc_integration_test
          - tests::neon_integrations::test_chainwork_first_intervals
          - tests::neon_integrations::test_chainwork_partial_interval
          - tests::neon_integrations::test_flash_block_skip_tenure
          - tests::neon_integrations::test_problematic_blocks_are_not_mined
          - tests::neon_integrations::test_problematic_blocks_are_not_relayed_or_stored
          - tests::neon_integrations::test_problematic_microblocks_are_not_mined
          - tests::neon_integrations::test_problematic_microblocks_are_not_relayed_or_stored
          - tests::neon_integrations::test_problematic_txs_are_not_stored
          - tests::neon_integrations::use_latest_tip_integration_test
          - tests::should_succeed_handling_malformed_and_valid_txs
    steps:
      - name: Checkout the latest code
        id: git_checkout
        run: |
          echo "Checkout the latest code"

      - name: Setup Rust Toolchain
        id: setup_rust_toolchain
        run: |
          echo "Setup Rust Toolchain"

      - name: Restore Cargo Cache
        id: restore_cargo_cache
        run: |
          echo "Restore Cargo Cache"

      - name: Restore Bitcoin Binary Cache
        id: restore_bitcoin_cache
        run: |
          echo "Restore Bitcoin Binary Cache"

      - name: Restore Test Archive Cache
        id: restore_test-archive_cache
        run: |
          echo "Restore Test Archive Cache"

      - name: Restore Target Cache
        id: restore_target_cache
        run: |
          echo "Restore Target Cache"

      - name: Link Bitcoin Binary
        id: bitcoin_binary
        run: |
          echo "Link Bitcoin Binary"

      - name: Run Tests
        id: run_tests
        run: |
          echo "Run Test ${{ matrix.test-name }}"

      - name: Run grcov
        id: run_grcov
        run: |
          echo "Run grcov"

      - name: Upload Code Coverage
        id: code_coverage
        run: |
          echo "Upload Code Coverage"
