##
## Create the github release and store artifact files (with checksum)
##

name: CI Tests

# Only run when:
#   - manually triggered via the ci.yml workflow

on:
  # push:
  #   tags:
  #     - "[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+" # 2.1.0.0.0
  #     - "[0-9]+.[0-9]+.[0-9].[0-9]+.[0-9]+-rc[0-9]+" # 2.1.0.0.0-rc1
  # workflow_run:
  #   workflows: ["Build Distributable Assets"]
  #   types:
  #     - completed
  workflow_call:
    inputs:
      workflow:
        description: "The workflow to run from a calling action"
        required: false
        type: string
  workflow_dispatch:
    inputs:
      workflow:
        description: "The workflow to run"
        required: true
        type: choice
        options:
          - atlas
          - bitcoin
          - epoch
          - slow
          - stacks-blockchain
jobs:
  create-cache:
    if: inputs.tag != ''
    name: Create Test Cache
    uses: ./.github/workflows/create-cache.yml
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  echo:
    name: Echo Input
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "input: ${{ inputs.workflow }}"
          echo "tag: ${{ inputs.tag }}"

  atlas-wf-test:
    if: |
      inputs.tag != '' &&
      inputs.workflow == 'atlas'
    name: Atlas Workflow Test
    runs-on: ubuntu-latest
    needs:
      - create-cache
    steps:
      - name: echo
        run: |
          echo "workflow test (atlas)"

  atlas-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      (
        inputs.tag != '' ||
        inputs.workflow == 'atlas'
      )
    name: Atlas Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/atlas-tests.yml

  # bitcoin-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.workflow == 'bitcoin tests'
  #   name: Bitcoin Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (bitcoin)"

  # epoch-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.workflow == 'epoch tests'
  #   name: Epoch Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (epoch)"

  # slow-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.workflow == 'slow tests'
  #   name: Epoch Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (slow)"

  # stacks-wf-test:
  #   if: |
  #     inputs.tag != '' &&
  #     inputs.workflow == 'stacks-blockchain tests'
  #   name: stacks-blockchain Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (stacks-blockchain)"

  bitcoin-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      (
        inputs.tag != '' ||
        inputs.workflow == 'Bitcoin Tests'
      )
    name: Bitcoin Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/bitcoin-tests.yml

  epoch-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      (
        inputs.tag != '' ||
        inputs.workflow == 'Epoch Tests'
      )
    name: Epoch Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/epoch-tests.yml

  slow-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      (
        inputs.tag != '' ||
        inputs.workflow == 'Slow Tests'
      )
    name: Slow Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/slow-tests.yml

  stacks-blockchain-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      (
        inputs.tag != '' ||
        inputs.workflow == 'Stacks Blockchain Tests'
      )
    name: Stacks Blockchain Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/stacks-blockchain-tests.yml
