##
## Create the github release and store artifact files (with checksum)
##

name: CI Tests

# Only run when:
#   - manually triggered via the ci.yml workflow

on:
  # push:
  #   tags:
  #     - "[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+" # 2.1.0.0.0
  #     - "[0-9]+.[0-9]+.[0-9].[0-9]+.[0-9]+-rc[0-9]+" # 2.1.0.0.0-rc1
  # workflow_run:
  #   workflows: ["Build Distributable Assets"]
  #   types:
  #     - completed
  workflow_call:
    inputs:
      test:
        description: "The workflow to run from a calling action"
        required: false
        type: string
  workflow_dispatch:
    inputs:
      test:
        description: "The tag to create (optional)"
        required: true
        type: choice
        options:
          - Atlas Tests
          - Bitcoin Tests
          - Epoch Tests
          - Slow Tests
          - Stacks-Blockchain Tests
jobs:
  create-cache:
    # if: inputs.tag != ''
    if: |
      inputs.tag != '' || (
        inputs.tag == '' &&
        inputs.test != ''
      )
    name: Create Test Cache
    uses: ./.github/workflows/create-cache.yml
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  echo:
    name: Echo Input
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "input: ${{ inputs.test }}"
          echo "tag: ${{ inputs.tag }}"
          echo "atlas truthy: ${{ ( inputs.tag == '' && inputs.test == 'Atlas Tests' ) || inputs.tag != ''}}"
          echo "bitcoin truthy: ${{ ( inputs.tag == '' && inputs.test == 'Bitcoin Tests' ) || inputs.tag != ''}}"
          echo "epoch truthy: ${{ ( inputs.tag == '' && inputs.test == 'Epoch Tests' ) || inputs.tag != ''}}"
          echo "slow truthy: ${{ ( inputs.tag == '' && inputs.test == 'Slow Tests' ) || inputs.tag != ''}}"
          echo "stacks-blockchain truthy: ${{ ( inputs.tag == '' && inputs.test == 'Stacks-Blockchain Tests' ) || inputs.tag != ''}}"

  # atlas-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.test == 'Atlas Tests'
  #   name: Atlas Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (atlas)"
  atlas-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      inputs.tag != '' || (
        inputs.tag == '' &&
        inputs.test == 'Atlas Tests'
      )
    name: Atlas Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/atlas-tests.yml

  # bitcoin-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.test == 'Bitcoin Tests'
  #   name: Bitcoin Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (bitcoin)"
  bitcoin-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      inputs.tag != '' || (
        inputs.tag == '' &&
        inputs.test == 'Bitcoin Tests'
      )
    name: Bitcoin Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/bitcoin-tests.yml

  # epoch-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.test == 'Epoch Tests'
  #   name: Epoch Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (epoch)"
  epoch-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      inputs.tag != '' || (
        inputs.tag == '' &&
        inputs.test == 'Epoch Tests'
      )
    name: Epoch Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/epoch-tests.yml

  # slow-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.test == 'Slow Tests'
  #   name: Slow Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (slow)"
  slow-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      inputs.tag != '' || (
        inputs.tag == '' &&
        inputs.test == 'Slow Tests'
      )
    name: Slow Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/slow-tests.yml

  # stacks-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.test == 'Stacks-Blockchain Tests'
  #   name: stacks-blockchain Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (stacks-blockchain)"

  stacks-blockchain-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      inputs.tag != '' || (
        inputs.tag == '' &&
        inputs.test == 'Stacks-Blockchain Tests'
      )
    name: Stacks Blockchain Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/stacks-blockchain-tests.yml
