##
## Create the github release and store artifact files (with checksum)
##

name: CI Tests

# Only run when:
#   - manually triggered via the ci.yml workflow

on:
  # push:
  #   tags:
  #     - "[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+" # 2.1.0.0.0
  #     - "[0-9]+.[0-9]+.[0-9].[0-9]+.[0-9]+-rc[0-9]+" # 2.1.0.0.0-rc1
  # workflow_run:
  #   workflows: ["Build Distributable Assets"]
  #   types:
  #     - completed
  # workflow_call:
  #   inputs:
  #     workflow:
  #       description: "The workflow to run from a calling action"
  #       required: false
  #       type: string
  workflow_call:
    # inputs:
    #   tag:
    #     description: "Tag name of this release (x.y.z)"
    #     required: false
    #     type: string
  workflow_dispatch:
    inputs:
      # tag:
      #   description: "Tag name of this release (x.y.z)"
      #   required: false
      #   type: string
      workflow:
        description: "The tag to create (optional)"
        required: true
        type: choice
        options:
          - All Tests
          - Atlas Tests
          - Bitcoin Tests
          - Epoch Tests
          - Slow Tests
          - Stacks-Blockchain Tests
jobs:
  create-cache:
    # if: inputs.tag != ''
    if: |
      (
        github.event_name == 'workflow_dispatch' &&
        inputs.workflow != ''
      )
    name: Create Test Cache
    uses: ./.github/workflows/create-cache.yml
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  echo:
    name: Echo Input
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "inputs.workflow: ${{ inputs.workflow }}"
          echo "github.event_name: ${{ github.event_name }}"
  # atlas-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.workflow == 'Atlas Tests'
  #   name: Atlas Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (atlas)"
  atlas-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      (
        github.event_name == 'workflow_dispatch' &&
        inputs.workflow != ''
      )
    # inputs.tag != '' || (
    #   inputs.tag == '' && (
    #     inputs.workflow == 'Atlas Tests' ||
    #     inputs.workflow == 'All Tests'
    #   )
    # )
    name: Atlas Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/atlas-tests.yml

  # bitcoin-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.workflow == 'Bitcoin Tests'
  #   name: Bitcoin Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (bitcoin)"
  bitcoin-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      (
        github.event_name == 'workflow_dispatch' &&
        inputs.workflow != ''
      )
    # inputs.tag != '' || (
    #   inputs.tag == '' && (
    #     inputs.workflow == 'Atlas Tests' ||
    #     inputs.workflow == 'All Tests'
    #   )
    # )
    name: Bitcoin Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/bitcoin-tests.yml

  # epoch-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.workflow == 'Epoch Tests'
  #   name: Epoch Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (epoch)"
  epoch-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      (
        github.event_name == 'workflow_dispatch' &&
        inputs.workflow != ''
      )
    # inputs.tag != '' || (
    #   inputs.tag == '' && (
    #     inputs.workflow == 'Atlas Tests' ||
    #     inputs.workflow == 'All Tests'
    #   )
    # )
    name: Epoch Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/epoch-tests.yml

  # slow-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.workflow == 'Slow Tests'
  #   name: Slow Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (slow)"
  slow-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      (
        github.event_name == 'workflow_dispatch' &&
        inputs.workflow != ''
      )
    # inputs.tag != '' || (
    #   inputs.tag == '' && (
    #     inputs.workflow == 'Atlas Tests' ||
    #     inputs.workflow == 'All Tests'
    #   )
    # )
    name: Slow Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/slow-tests.yml

  # stacks-wf-test:
  #   if: |
  #     inputs.tag == '' &&
  #     inputs.workflow == 'Stacks-Blockchain Tests'
  #   name: stacks-blockchain Workflow Test
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - create-cache
  #   steps:
  #     - name: echo
  #       run: |
  #         echo "workflow test (stacks-blockchain)"

  stacks-blockchain-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: |
      (
        github.event_name == 'workflow_dispatch' &&
        inputs.workflow != ''
      )
    # inputs.tag != '' || (
    #   inputs.tag == '' && (
    #     inputs.workflow == 'Atlas Tests' ||
    #     inputs.workflow == 'All Tests'
    #   )
    # )
    name: Stacks Blockchain Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/stacks-blockchain-tests.yml
