##
## Create the github release and store artifact files (with checksum)
##

name: CI Tests

# Only run when:
#   - manually triggered via the ci.yml workflow

on:
  # push:
  #   tags:
  #     - "[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+" # 2.1.0.0.0
  #     - "[0-9]+.[0-9]+.[0-9].[0-9]+.[0-9]+-rc[0-9]+" # 2.1.0.0.0-rc1
  # workflow_run:
  #   workflows: ["Build Distributable Assets"]
  #   types:
  #     - completed
  workflow_call:
  workflow_dispatch:
    inputs:
      workflow:
        description: "The tag to create (optional)"
        required: true
        type: choice
        options:
          - atlas
          - bitcoin
          - epoch
          - slow
          - stacks-blockchain
jobs:
  create-cache:
    if: inputs.tag != ''
    name: Create Test Cache
    uses: ./.github/workflows/create-cache.yml
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  atlas-wf-test:
    if: |
      inputs.tag == '' &&
      inputs.workflow == 'atlas'
    name: Atlas Workflow Test
    runs-on: ubuntu-latest
    # needs:
    #   - create-cache
    steps:
      - name: echo
        run: |
          echo "workflow test (atlas)"

  bitcoin-wf-test:
    if: |
      inputs.tag == '' &&
      inputs.workflow == 'bitcoin'
    name: Bitcoin Workflow Test
    runs-on: ubuntu-latest
    # needs:
    #   - create-cache
    steps:
      - name: echo
        run: |
          echo "workflow test (bitcoin)"

  epoch-wf-test:
    if: |
      inputs.tag == '' &&
      inputs.workflow == 'atlas'
    name: Epoch Workflow Test
    runs-on: ubuntu-latest
    # needs:
    #   - create-cache
    steps:
      - name: echo
        run: |
          echo "workflow test (epoch)"

  slow-wf-test:
    if: |
      inputs.tag == '' &&
      inputs.workflow == 'slow'
    name: Epoch Workflow Test
    runs-on: ubuntu-latest
    # needs:
    #   - create-cache
    steps:
      - name: echo
        run: |
          echo "workflow test (slow)"

  stacks-wf-test:
    if: |
      inputs.tag != '' &&
      inputs.workflow == 'stacks-blockchain'
    name: stacks-blockchain Workflow Test
    runs-on: ubuntu-latest
    # needs:
    #   - create-cache
    steps:
      - name: echo
        run: |
          echo "workflow test (stacks-blockchain)"

  atlas-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: inputs.tag != ''
    name: Atlas Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/atlas-tests.yml

  bitcoin-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: inputs.tag != ''
    name: Bitcoin Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/bitcoin-tests.yml

  epoch-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: inputs.tag != ''
    name: Epoch Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/epoch-tests.yml

  slow-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: inputs.tag != ''
    name: Slow Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/slow-tests.yml

  stacks-blockchain-tests:
    # if: ${{ inputs.tag != '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    if: inputs.tag != ''
    name: Stacks Blockchain Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/stacks-blockchain-tests.yml
