# ref: https://github.com/easimon/maximize-build-space/blob/master/action.yml
# this should be good enough, but in the future we may want to setup LVM like in the linked action (they do note it may break in the future, and is hacky)

name: Runner Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup-disk:
    name: Runner Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Reclaim disk space
        id: cleanup
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo apt-get autoremove -y
          sudo apt-get clean
          docker system prune --force

