##
## Create Cache
##

name: Create Test Caches

# Run when:
#   - PR is approved
#     - files changed are *.rs or *.clar (i.e. no .yml or .md files)
#  https://github.com/marketplace/actions/paths-changes-filter

on:
  # workflow_dispatch:
  workflow_call:
  # pull_request_review:
  #   types: [submitted]
  # pull_request_target:
  #   paths:
  #     - "**.rs"
  #     - "**.clar"

defaults:
  run:
    shell: bash

env:
  RUSTFLAGS: "-Cinstrument-coverage"
  LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
  BTC_VERSION: "0.20.0"

concurrency:
  # group: stacks-bitcoin-cache-${{ github.ref }}
  # # Only cancel in progress if this is for a PR
  # cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: create-cache-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  cache-cargo:
    # if: github.event.review.state == 'approved'
    name: Cargo Cache
    runs-on: ubuntu-latest
    # runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: echo
        run: |
          echo "cargo cache"
          echo "inputs.tag: ${{ inputs.tag }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.action: ${{ github.event.action }}"
          echo "github.event.review.state: ${{ github.event.review.state }}"
          echo "truthy: ${{ inputs.tag == '' || ( github.event_name == 'pull_request_review' && github.event.action == 'submitted' && github.event.review.state == 'approved' }}"
  ##
  ## it is expected that this cache will exist longer so other runs can use it
  ##

  cache-bitcoin-binary:
    # if: github.event.review.state == 'approved'
    name: Bitcoin Binary Cache
    runs-on: ubuntu-latest
    # runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: echo
        run: |
          echo "cache-bitcoin-binary"

  cache-test-archive:
    # if: github.event.review.state == 'approved'
    name: Test Archive Cache
    runs-on: ubuntu-latest
    # runs-on: buildjet-4vcpu-ubuntu-2204
    needs:
      - cache-cargo
    steps:
      - name: echo
        run: |
          echo "cache-test-archive"
