## Github workflow to create reusable caches

name: Create Test Cache

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  # RUSTFLAGS: "-Cinstrument-coverage -Dwarnings"
  RUSTFLAGS: "-Cinstrument-coverage -Awarnings"
  LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
  BTC_VERSION: "0.20.0"

##
## Cache will exist longer than workflow execution so other runners have access
##   ex: a failed job should have access to the cache for however long `cleanup.yml` is set to delete old caches
##       however, this is only relevant if the commit sha does not change between runs

jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    steps:
      ## Perform a lookup to check if the cache already exists
      - name: Cargo Cache
        id: cargo-cache
        uses: wileyj/actions/stacks-blockchain/cache/cargo@main
        with:
          action: save

  bitcoin-binary:
    name: Bitcoin Binary
    runs-on: ubuntu-latest
    steps:
      - name: Bitcoin Cache
        id: bitcoin-cache
        uses: wileyj/actions/stacks-blockchain/cache/bitcoin@main
        with:
          action: save

  nextest-archive:
    name: Test Archive
    runs-on: ubuntu-latest
    needs:
      - cargo
    steps:
      - name: Cache Nexttest Archives
        id: cache-test-archives
        uses: wileyj/actions/stacks-blockchain/cache/archive-tests@main
        with:
          genesis: true