# Only run when:
#   - called manually
#   - cron

name: Delete Actions

on:
  workflow_dispatch:
  workflow_call:
  # schedule:
  #   - cron: '0 0 * * *'  # every day at midnight

concurrency:
  # group: ${{ github.head_ref || github.run_id }}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  EPOCH_30: 2592000 # seconds in 30 days
  EPOCH_14: 1209600 # seconds in 14 days
  EPOCH_7: 44800 # seconds in 7 days
  EPOCH_1: 86400 # seconds in 1 day

defaults:
  run:
    shell: bash

jobs:
  # maybe run this via cron to delete all actions older than x days
  delete-old-actions:
    # if: ${{ false }}
    name: Delete Actions
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          TS=$(date --iso-8601=ns -u -d @$((EPOCHSECONDS-${{ env.EPOCH_1 }})))
          echo "github.repository: ${{ github.repository }}"
          echo "TS: ${TS}"
          gh extension install actions/gh-actions-cache
          gh api \
            --paginate \
            -H "Accept: application/vnd.github+json" \
            repos/${{ github.repository }}/actions/runs |
          for ID in `
            jq -r --arg TS "$TS" '
              .workflow_runs[]
              | { id, updated_at,  }
              | select(.updated_at < $TS)
              | {id}
              | .[]
            '
          `; do
            echo "*** Deleting action: $ID (https://github.com/${{ github.repository }}/actions/runs/${ID})"
            gh api \
              -H "Accept: application/vnd.github.v3+json" \
              -X DELETE \
              repos/${{ github.repository }}/actions/runs/$ID \
            | echo;
          done
          echo "Done"
