# Only run when:
#   - called manually
#   - cron

name: Delete Cache

on:
  workflow_dispatch:
  workflow_call:
  # schedule:
  #   - cron: '0 0 * * *'  # every day at midnight

concurrency:
  # group: ${{ github.head_ref || github.run_id }}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  EPOCH_30: 2592000 # seconds in 30 days
  EPOCH_14: 1209600 # seconds in 14 days
  EPOCH_7: 44800 # seconds in 7 days
  EPOCH_1: 86400 # seconds in 1 day

defaults:
  run:
    shell: bash

jobs:
  # maybe run this via cron to delete all caches older than 1 day
  # AND run this at the end of ci.yml to delete all caches if the workflow is fully successful
  delete-old-cache:
    # if: ${{ false }}
    name: Delete Caches
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          TS=$(date --iso-8601=ns -u -d @$((EPOCHSECONDS-${{ env.EPOCH_1 }})))
          echo "Deleting all caches older than: ${TS}"
          gh extension install actions/gh-actions-cache
          gh api \
            --paginate \
            -H "Accept: application/vnd.github+json" \
            repos/${{ github.repository }}/actions/caches |
          for ID in `
            jq -r --arg TS "$TS" '
              .actions_caches[]
              | { id, last_accessed_at, key }
              | select(.last_accessed_at < $TS)
              | {id}
              | .[]
            '
          `; do
            echo "*** Deleting cache: $ID"
            gh api \
              -H "Accept: application/vnd.github.v3+json" \
              -X DELETE \
              repos/${{ github.repository }}/actions/caches/$ID \
            | echo;
          done
          echo "Done"
