# Only run when:
#   - called manually or from another workflow

name: Delete Cache

on:
  workflow_dispatch:
  workflow_call:
concurrency:
  # group: ${{ github.head_ref || github.run_id }}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  # maybe run this via cron to delete all caches older than 1 day
  # AND run this at the end of ci.yml to delete all caches if the workflow is fully successful
  delete-old-cache:
    # if: ${{ false }}
    name: Delete Cache
    runs-on: ubuntu-latest
    steps:
      - name: Delete Binary Cache
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete ${{ github.event.repository.name }}-cargo -R ${{ github.repository }} --confirm
          gh actions-cache delete ${{ github.event.repository.name }}-target -R ${{ github.repository }} --confirm
          gh actions-cache delete ${{ github.event.repository.name }}-test-archive -R ${{ github.repository }} --confirm
          gh actions-cache delete ${{ github.event.repository.name }}-genesis-archive -R ${{ github.repository }} --confirm
          echo "Done"
        # run: |
        #   TS=$(date --iso-8601=ns -u -d @$((EPOCHSECONDS-86400)))
        #   gh api \
        #     --paginate \
        #     -H "Accept: application/vnd.github+json" \
        #     repos/${{ github.repository }}/actions/caches |
        #   for ID in `
        #     jq -r --arg TS "$TS" '
        #       .actions_caches[]
        #       | { id, last_accessed_at, key }
        #       | select(.last_accessed_at < $TS)
        #       | {id}
        #       | .[]
        #     '
        #   `; do
        #     echo "deleting cache: $ID"
        #     gh api \
        #       -H "Accept: application/vnd.github.v3+json" \
        #       -X DELETE \
        #       repos/${{ github.repository }}/actions/caches/$ID \
        #     | echo;
        #   done

  # delete-workflow-cache:
  #   # if: ${{ false }}
  #   name: Delete Cache
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Delete Binary Cache
  #       env:
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #       run: |
  #         gh extension install actions/gh-actions-cache
  #         gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-cargo -R ${{ github.repository }} --confirm
  #         gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-target -R ${{ github.repository }} --confirm
  #         gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-test-archive -R ${{ github.repository }} --confirm
  #         gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-genesis-archive -R ${{ github.repository }} --confirm
  #         echo "Done"

# https://github.com/actions/upload-artifact/issues/290#issuecomment-1374207010
# https://github.com/marketplace/actions/purge-cache
# https://github.com/marketplace/actions/delete-run-artifacts
# https://github.com/marketplace/actions/rerun-actions
