# Only run when:
#   - called manually or from another workflow

name: Delete Cache

on:
  workflow_dispatch:
  workflow_call:
concurrency:
  # group: ${{ github.head_ref || github.run_id }}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  delete-cache:
    # if: ${{ false }}
    name: Delete Cache
    runs-on: ubuntu-latest
    steps:
      - name: Delete Binary Cache
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete ${{ github.event.repository.name }}-cargo -R ${{ github.repository }} --confirm
          gh actions-cache delete ${{ github.event.repository.name }}-target -R ${{ github.repository }} --confirm
          gh actions-cache delete ${{ github.event.repository.name }}-test-archive -R ${{ github.repository }} --confirm
          gh actions-cache delete ${{ github.event.repository.name }}-genesis-archive -R ${{ github.repository }} --confirm
          echo "Done"
        # run: |
        #   for cache in $(gh actions-cache list -R ${{ github.repository }}  | grep ${{ github.run_id }}-${{ github.sha }} | awk {'print $1'}); do
        #     echo "Deleting cache ${cache}"
        #     gh actions-cache delete -R ${{ github.repository }} ${cache} --confirm
        #   done

      # - name: Delete Rust Cache
      #   env:
      #     REPO: ${{ github.repository }}
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: |
      #     gh extension install actions/gh-actions-cache
      #     gh actions-cache delete v0-rust-integration-tests-${{ github.run_id }}-${{ github.sha }} -R ${{ github.repository }} --confirm
      #     gh actions-cache delete v0-rust-epoch-tests-${{ github.run_id }}-${{ github.sha }} -R ${{ github.repository }} --confirm
      #     gh actions-cache delete v0-rust-atlas-tests-${{ github.run_id }}-${{ github.sha }} -R ${{ github.repository }} --confirm
      #     gh actions-cache delete v0-rust-slow-tests-${{ github.run_id }}-${{ github.sha }} -R ${{ github.repository }} --confirm
      #     gh actions-cache delete v0-rust-full-genesis-${{ github.run_id }}-${{ github.sha }} -R ${{ github.repository }} --confirm
      #     gh actions-cache delete v0-rust-unit-tests-${{ github.run_id }}-${{ github.sha }} -R ${{ github.repository }} --confirm
      #     echo "Done"

# for cache in $(gh actions-cache list -R ${{ github.repository }}  | grep ${{ github.run_id }}-${{ github.sha }} | awk {'print $1'}); do
#   echo "Deleting cache ${cache}"
#   gh actions-cache delete -R ${{ github.repository }} ${cache} --confirm
# done
#

# run: |
#   gh extension install actions/gh-actions-cache
#   gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-cargo -R ${{ github.repository }} --confirm
#   gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-target -R ${{ github.repository }} --confirm
#   gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-test-archive -R ${{ github.repository }} --confirm
#   gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-genesis-archive -R ${{ github.repository }} --confirm
#   echo "Done"
# run: |
#   gh extension install actions/gh-actions-cache
#   gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_id }}-cargo -R ${{ github.repository }} --confirm
#   gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_id }}-target -R ${{ github.repository }} --confirm
#   gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_id }}-test-archive -R ${{ github.repository }} --confirm
#   gh actions-cache delete ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_id }}-genesis-archive -R ${{ github.repository }} --confirm
#   echo "Done"

# https://github.com/actions/upload-artifact/issues/290#issuecomment-1374207010
# https://github.com/marketplace/actions/purge-cache
# https://github.com/marketplace/actions/delete-run-artifacts
# https://github.com/marketplace/actions/rerun-actions
