# https://cli.github.com/manual/gh_pr_create
on:
  push:
    branches:
      - master
      - develop

permissions:
  pull-requests: write

jobs:
  create-pr:
    name: Create Downstream PR
    runs-on: ubuntu-latest
    steps:
      - name: Open Downstream PR (${{ github.ref_name }})
        id: create-pr
        uses: wileyj/actions/stacks-core/downstream-pr@main
        with:
          token: ${{ secrets.GH_TOKEN }}
