## Github workflow to run epoch tests

name: Tests::Epoch

on:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15
  RETRIES: 3
  RETRY_DELAY: 10000

concurrency:
  group: epoch-tests-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # epoch tests with code coverage
  epoch-tests:
    name: Epoch Tests
    runs-on: ubuntu-latest
    ## continue tests even if we have a failure
    continue-on-error: true
    ## run a maximum of 2 concurrent tests from the test matrix
    strategy:
      ## continue with the matrix even if we've had a failure
      fail-fast: false
      max-parallel: 32
      matrix:
        test-name:
          - tests::epoch_205::bigger_microblock_streams_in_2_05
          - tests::epoch_205::test_cost_limit_switch_version205
          - tests::epoch_205::test_dynamic_db_method_costs
          - tests::epoch_205::test_exact_block_costs
          - tests::epoch_205::transition_empty_blocks
          - tests::epoch_21::test_pox_missing_five_anchor_blocks
          - tests::epoch_21::test_pox_reorg_one_flap
          - tests::epoch_21::test_pox_reorgs_three_flaps
          - tests::epoch_21::test_sortition_divergence_pre_21
          - tests::epoch_21::test_v1_unlock_height_with_current_stackers
          - tests::epoch_21::test_v1_unlock_height_with_delay_and_current_stackers
          - tests::epoch_21::trait_invocation_cross_epoch
          - tests::epoch_21::transition_adds_burn_block_height
          - tests::epoch_21::transition_adds_get_pox_addr_recipients
          - tests::epoch_21::transition_adds_mining_from_segwit
          - tests::epoch_21::transition_adds_pay_to_contract
          - tests::epoch_21::transition_empty_blocks
          - tests::epoch_21::transition_fixes_bitcoin_rigidity
          - tests::epoch_21::transition_removes_pox_sunset
          - tests::epoch_22::disable_pox
          - tests::epoch_22::pox_2_unlock_all
          - tests::epoch_22::test_pox_reorg_one_flap
          - tests::epoch_23::trait_invocation_behavior
          - tests::epoch_24::fix_to_pox_contract
          - tests::epoch_24::verify_auto_unlock_behavior
    steps:
      ## Setup test environment
      - name:  Setup Test Environment
        id: setup_tests
        uses: stacks-network/actionsstacks-blockchain/testenv@main

      ## Run test matrix using cached archive file
      - name: Run Tests
        id: run_tests
        timeout-minutes: 30
        run: |
          cargo nextest run \
            --test-threads 1 \
            --run-ignored all \
            --retries 2 \
            --final-status-level fail \
            --fail-fast \
            --archive-file /tmp/test_archive.tar.zst \
            "${{ matrix.test-name }}"

      ## Create and upload code coverage
      - name: Code Coverage
        id: codecov
        uses: stacks-network/actionscodecov@main
        with:
          test-name: ${{ matrix.test-name }}
