name: Docker Image (Source)

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

## Define which docker arch to build for
env:
  docker_platforms: linux/amd64

jobs:
  ## Runs anytime `ci.yml` runs or when manually called
  image:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      ## Build a maximum of 2 images concurrently based on matrix.dist
      max-parallel: 2
      matrix:
        dist:
          - debian
    steps:
      ## Checkout the code
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3

      ## Set some vars to be used in the build process
      - name: Set Vars
        id: set_vars
        run: |
          event=${{ github.event_name }}
          case ${event} in
            pull_request|pull_request_target|pull_request_review)
              echo "[PR]: true"
              branch=${{ github.event.pull_request.head.ref }}
              ;;
            *)
              echo "[PR]: false"
              branch=${GITHUB_REF#refs/heads/}
              ;;
          esac
          echo "BRANCH_NAME=$branch" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      ## Setup QEMU for multi-arch builds
      - name: Set up QEMU
        id: docker_qemu
        uses: docker/setup-qemu-action@v2

      ## Setup docker buildx
      - name: Set up Docker Buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@v2

      ## Login to dockerhub
      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

        ## Set docker metatdata
      - name: Docker Metadata ( ${{matrix.dist}} )
        id: docker_metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            wileyj/${{ github.event.repository.name }}
          tags: |
            type=raw,value=${{ env.BRANCH_NAME }}
            type=ref,event=pr

      ## Build docker image
      - name: Build and Push ( ${{matrix.dist}} )
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./.github/actions/dockerfiles/Dockerfile.${{matrix.dist}}-source
          platforms: ${{ env.docker_platforms }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          build-args: |
            STACKS_NODE_VERSION=${{ env.GITHUB_SHA_SHORT }}
            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
          push: true
