# https://github.com/dessant/lock-threads

name: "Lock Threads"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  ## Lock closed issues/prs/discussions
  cargo:
    name: Lock Threads
    runs-on: ubuntu-latest
    steps:
      ## Perform a lookup to check if the cache already exists
      - name: Lock Threads
        id: lock_threads
        uses: stacks-network/actions/lock-threads@feat/lock-threads
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          process-only: "issues,prs"
