##
## Create the github release and store artifact files (with checksum)
##

name: Tests

# Only run when:
#   - manually triggered via the ci.yml workflow

on:
  # push:
  #   tags:
  #     - "[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+" # 2.1.0.0.0
  #     - "[0-9]+.[0-9]+.[0-9].[0-9]+.[0-9]+-rc[0-9]+" # 2.1.0.0.0-rc1
  # workflow_run:
  #   workflows: ["Build Distributable Assets"]
  #   types:
  #     - completed
  # workflow_call:
  #   inputs:
  #     workflow:
  #       description: "The workflow to run from a calling action"
  #       required: false
  #       type: string
  # workflow_call:
  #   inputs:
  #     workflow:
  #       description: "Tests to run (required)"
  #       required: true
  #       type: string
  workflow_dispatch:
    inputs:
      workflow:
        description: "Tests to run (required)"
        required: true
        type: choice
        options:
          - All Tests
          - CI Tests
          - Atlas Tests
          - Bitcoin Tests
          - Epoch Tests
          - Slow Tests
          - Stacks-Blockchain Tests
jobs:
  create-cache:
    name: Create Test Cache
    uses: ./.github/workflows/create-cache.yml
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  atlas-tests:
    if: |
      (
        inputs.workflow == 'All Tests' ||
        inputs.workflow == 'Atlas Tests' 
      )
    name: Atlas Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/atlas-tests.yml

  bitcoin-tests:
    if: |
      (
        inputs.workflow == 'All Tests' ||
        inputs.workflow == 'CI Tests' ||
        inputs.workflow == 'Bitcoin Tests'
      )
    name: Bitcoin Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/bitcoin-tests.yml

  epoch-tests:
    if: |
      (
        inputs.workflow == 'All Tests' ||
        inputs.workflow == 'CI Tests' ||
        inputs.workflow == 'Epoch Tests'
      )
    name: Epoch Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/epoch-tests.yml

  slow-tests:
    if: |
      (
        inputs.workflow == 'All Tests' ||
        inputs.workflow == 'Slow Tests'
      )
    name: Slow Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/slow-tests.yml

  stacks-blockchain-tests:
    if: |
      (
        inputs.workflow == 'All Tests' ||
        inputs.workflow == 'Stacks-Blockchain Tests'
      )
    name: Stacks Blockchain Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/stacks-blockchain-tests.yml
