##
## Run Tests
##

name: Run Tests

# Only run when:
#   - PRs are (re)opened against master branch

on:
  ## run when tagging a release or a PR is approved
  workflow_dispatch:
  workflow_call:
  # push:
  #   tags:
  #     - "[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+" # 2.1.0.0.0
  #     - "[0-9]+.[0-9]+.[0-9].[0-9]+.[0-9]+-rc[0-9]+" # 2.1.0.0.0-rc1
  pull_request_review:
    types: [submitted]

concurrency:
  # group: stacks-bitcoin-cache-${{ github.ref }}
  # # Only cancel in progress if this is for a PR
  # cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: run-tests-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  create-cache:
    name: Create Test Cache
    uses: ./.github/workflows/create-cache.yml
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  bitcoin-tests:
    name: Run Bitcoin Tests
    uses: ./.github/workflows/bitcoin-tests.yml
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  stacks-blockchain-tests:
    name: Run Bitcoin Tests
    uses: ./.github/workflows/stacks-blockchain-tests.yml
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  release-tests:
    name: Run Bitcoin Tests
    uses: ./.github/workflows/release-tests.yml
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  # slow-tests:
  #   name: Run Bitcoin Tests
  #   uses: ./.github/workflows/slow-test.yml
  #   needs:
  #     - create-cache
  #   # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  delete-cache:
    name: Run Bitcoin Tests
    uses: ./.github/workflows/delete-cache.yml
    needs:
      - create-cache
      - bitcoin-tests
      - stacks-blockchain-tests
      - release-tests
      # - slow-tests
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master
