## Github workflow to run slow tests

name: Tests::Slow

on:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15
  RETRIES: 3
  RETRY_DELAY: 10000

concurrency:
  group: slow-tests-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # slow tests with code coverage
  slow-tests:
    name: Slow Tests
    runs-on: ubuntu-latest
    ## continue tests even if we have a failure
    continue-on-error: true
    ## run a maximum of 2 concurrent tests from the test matrix
    strategy:
      ## continue with the matrix even if we've had a failure
      fail-fast: false
      max-parallel: 2
      matrix:
        test-name:
          - tests::epoch_21::test_pox_reorg_flap_duel
          - tests::epoch_21::test_pox_reorg_flap_reward_cycles ## really, really slow test
    steps:
      ## Setup test environment
      - name:  Setup Test Environment
        id: setup_tests
        uses: stacks-network/actionsstacks-blockchain/testenv@main

      ## Run test matrix using cached archive file
      ##   - timeout after 30 minutes
      - name: Run Tests
        id: run_tests
        timeout-minutes: 30
        run: |
          cargo nextest run \
            --test-threads 1 \
            --run-ignored all \
            --retries 2 \
            --final-status-level fail \
            --fail-fast \
            --archive-file /tmp/test_archive.tar.zst \
            "${{ matrix.test-name }}"

      ## Create and upload code coverage
      - name: Code Coverage
        id: codecov
        uses: stacks-network/actionscodecov@main
        with:
          test-name: ${{ matrix.test-name }}
