## Github workflow to run slow tests

name: Tests::Slow

on:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15

concurrency:
  group: slow-tests-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # slow tests with code coverage
  slow-tests:
    name: Slow Tests
    runs-on: ubuntu-latest
    ## run a maximum of 2 concurrent tests from the test matrix
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        test-name:
          - tests::epoch_21::test_pox_reorg_flap_duel
          - tests::epoch_21::test_pox_reorg_flap_reward_cycles ## really, really slow test
    steps:
      ## cleanup runner
      - name: Cleanup Runner
        id: runner_cleanup
        uses: stacks-network/runner-cleanup@main

      ## Checkout the code
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      ## Install rust toolchain (llvm-tools-preview)
      - name: Setup Rust Toolchain
        id: setup_rust_toolchain
        uses: actions-rust-lang/setup-rust-toolchain@f3c84ee10bf5a86e7a5d607d487bf17d57670965 # v1.5.0
        with:
          toolchain: stable
          components: llvm-tools-preview
          cache: false

      ## Restore cargo cache data
      ##   - use wretry action, to retry on a failed upload 3x
      - name:  Restore Cargo Cache
        id: restore_cargo_cache
        uses: wileyj/runner-cache/cargo@main
        with:
          action: restore

      ## Restore nextest target cache data
      ##   - use wretry action, to retry on a failed upload 3x
      - name:  Restore Target Cache
        id: restore_target_cache
        uses: wileyj/runner-cache/target@main
        with:
          action: restore

      ## Restore bitcoin cache data
      ##   - use wretry action, to retry on a failed upload 3x
      - name:  Restore Bitcoin Binary Cache
        id: restore_bitcoin_cache
        uses: wileyj/runner-cache/bitcoin@main
        with:
          action: restore

      ## Restore genesis nextest archive cache data
      ##   - use wretry action, to retry on a failed upload 3x
      - name:  Restore Genesis Archive Cache
        id: restore_test
        uses: wileyj/runner-cache/genesis-test-archive@main
        with:
          action: restore

      ## Symlink bitoind to $PATH
      - name: Link Bitcoin Binary
        id: bitcoin_binary
        run: |
          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
          ls -al /bin/bitcoind

      ## Run test matrix using cached archive file
      ##   - timeout after 30 minutes
      - name: Run Tests
        id: run_tests
        timeout-minutes: 30
        run: |
          cargo nextest run \
            --test-threads 1 \
            --run-ignored all \
            --retries 2 \
            --final-status-level fail \
            --fail-fast \
            --archive-file /tmp/test_archive.tar.zst \
            "${{ matrix.test-name }}"

      ## Generate code coverage using grcov
      - name: Run grcov
        id: run_grcov
        run: |
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info || exit 1
          echo "created=true\n" >> $GITHUB_OUTPUT

      ## Upload coverage to codecov
      ##   - use wretry action, to retry on a failed upload 3x
      - name: Upload Code Coverage
        id: code_coverage
        uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
        with:
          action: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
          with: |
            files: ./lcov.info
            name: ${{ matrix.test-name }}
            fail_ci_if_error: false
            verbose: true
          attempt_limit: 3
          attempt_delay: 10000
