## Github workflow to run slow tests

name: Tests::Slow

on:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15

concurrency:
  group: slow-tests-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # slow tests with code coverage
  slow-tests:
    name: Slow Tests
    runs-on: ubuntu-latest
    ## run a maximum of 2 concurrent tests from the test matrix
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        test-name:
          - tests::epoch_21::test_pox_reorg_flap_duel
          - tests::epoch_21::test_pox_reorg_flap_reward_cycles ## really, really slow test
    steps:
      ## Checkout the code
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      ## Install rust toolchain (llvm-tools-preview)
      - name: Setup Rust Toolchain
        id: setup_rust_toolchain
        uses: actions-rust-lang/setup-rust-toolchain@f3c84ee10bf5a86e7a5d607d487bf17d57670965 # v1.5.0
        with:
          toolchain: stable
          components: llvm-tools-preview
          cache: false

      ## Restore cargo cache data
      - name: Restore Cargo Cache
        id: restore_cargo_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          # key: ${{ github.event.repository.name }}-cargo
          key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo

      ## Restore bitcoin cache data
      - name: Restore Bitcoin Binary Cache
        id: restore_bitcoin_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: /tmp/bitcoin
          key: ${{ github.event.repository.name }}-bitcoin-binaries

      ## Restore nextest archive cache data
      - name: Restore Test Archive Cache
        id: restore_test-archive_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: /tmp/test_archive.tar.zst
          # key: ${{ github.event.repository.name }}-test-archive
          key: ${{ github.event.repository.name }}-${{ github.sha }}-test-archive

      ## Restore nextest target cache data
      - name: Restore Target Cache
        id: restore_target_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: ./target
          # key: ${{ github.event.repository.name }}-target
          key: ${{ github.event.repository.name }}-${{ github.sha }}-target

      ## Symlink bitoind to $PATH
      - name: Link Bitcoin Binary
        id: bitcoin_binary
        run: |
          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
          ls -al /bin/bitcoind

      ## Run test matrix using cached archive file
      ##   - timeout after 30 minutes
      - name: Run Tests
        id: run_tests
        timeout-minutes: 30
        run: |
          cargo nextest run \
            --test-threads 1 \
            --run-ignored all \
            --retries 2 \
            --final-status-level fail \
            --fail-fast \
            --archive-file /tmp/test_archive.tar.zst \
            "${{ matrix.test-name }}"

      ## Generate code coverage using grcov
      - name: Run grcov
        id: run_grcov
        run: |
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info || exit 1
          echo "created=true\n" >> $GITHUB_OUTPUT

      ## Upload coverage to codecov
      ##   - use wretry action, to retry on a failed upload 3x
      - name: Upload Code Coverage
        id: code_coverage
        uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
        with:
          action: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
          with: |
            files: ./lcov.info
            name: ${{ matrix.test-name }}
            fail_ci_if_error: false
            verbose: true
          attempt_limit: 3
          attempt_delay: 10000
