##
## Stacks Blockchain Tests
##

name: Stacks Blockchain Tests

on:
  ## run when create-cache has completed successfully
  ##  create-cache will run when an input-tag is provided, or a PR is approved
  workflow_dispatch:
  workflow_call:
  # push:
  #   paths-ignore:
  #     - "**.md"
  #     - "**.yml"
  #   tags:
  #     - "[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+" # 2.1.0.0.0
  #     - "[0-9]+.[0-9]+.[0-9].[0-9]+.[0-9]+-rc[0-9]+" # 2.1.0.0.0-rc1
  # workflow_run:
  #   workflows: ["Create Test Caches"]
  #   types:
  #     - completed

defaults:
  run:
    shell: bash

env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15

concurrency:
  # https://github.com/orgs/community/discussions/13496
  # group: stacks-blockchain-tests-${{ github.ref }}
  group: stacks-blockchain-tests-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # check to see if cache exists, if not then recreate it
  create-cache:
    name: Create Test Cache
    uses: ./.github/workflows/create-cache.yml
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master

  # full genesis test with code coverage
  full-genesis:
    # if: ${{ false }}
    name: Full Genesis Test
    runs-on: ubuntu-latest
    needs:
      - create-cache
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        test-name:
          - neon_integrations::bitcoind_integration_test
    steps:
      - name: echo
        run: |
          echo "full-genesis"

  # unit tests with code coverage
  unit-tests:
    # if: ${{ false }}
    name: Unit Tests
    runs-on: ubuntu-latest
    needs:
      - create-cache
    steps:
      - name: echo
        run: |
          echo "unit-tests"

  open-api-validation:
    # if: ${{ false }}
    name: OpenAPI Validation
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "open-api-validation"

  # Disabled :: net-tests
  nettest:
    # disable this job/test for now, since we haven't seen this pass
    #  on github actions in a while, and the failures can take > 4 hours
    if: ${{ false }}
    name: Net-Test
    runs-on: ubuntu-latest
    # runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: echo
        run: |
          echo "nettest"

  # Core contract tests
  core-contracts-clarinet-test:
    name: Core Contracts Test
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "core-contracts-clarinet-test"
