##
## Stacks Blockchain Tests
##

name: Stacks Blockchain Tests

on:
  ## run when create-cache has completed successfully
  ##  create-cache will run when an input-tag is provided, or a PR is approved
  workflow_dispatch:
  workflow_call:
  # push:
  #   paths-ignore:
  #     - "**.md"
  #     - "**.yml"
  #   tags:
  #     - "[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+" # 2.1.0.0.0
  #     - "[0-9]+.[0-9]+.[0-9].[0-9]+.[0-9]+-rc[0-9]+" # 2.1.0.0.0-rc1
  # workflow_run:
  #   workflows: ["Create Test Caches"]
  #   types:
  #     - completed

defaults:
  run:
    shell: bash

env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15

concurrency:
  # https://github.com/orgs/community/discussions/13496
  # group: stacks-blockchain-tests-${{ github.ref }}
  group: stacks-blockchain-tests-${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # full genesis test with code coverage
  full-genesis:
    # if: ${{ false }}
    name: Full Genesis Test
    runs-on: ubuntu-latest
    # needs:
    #   - create-cache
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        test-name:
          - neon_integrations::bitcoind_integration_test
    steps:
      - name: echo
        run: |
          echo "full-genesis ${{ matrix.test-name }}"
          echo "inputs.tag: ${{ inputs.tag }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.action: ${{ github.event.action }}"
          echo "github.event.review.state: ${{ github.event.review.state }}"
          echo "true if (input || pr approval): ${{ inputs.tag == '' || ( github.event_name == 'pull_request_review' && github.event.action == 'submitted' && github.event.review.state == 'approved') }}"
          echo "true if (input && not (pr submitted && !(pr comment || pr change requested))): ${{ inputs.tag == '' &&  !( github.event_name == 'pull_request_review' &&  github.event.action == 'submitted' &&  ( github.event.review.state == 'commented' || github.event.review.state == 'changes_requested' ) ) }}"
