##
## Create the github release and store artifact files (with checksum)
##

name: Standalone Tests

# Only run when:
#   - manually triggered via the ci.yml workflow

on:
  # push:
  #   tags:
  #     - "[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+" # 2.1.0.0.0
  #     - "[0-9]+.[0-9]+.[0-9].[0-9]+.[0-9]+-rc[0-9]+" # 2.1.0.0.0-rc1
  # workflow_run:
  #   workflows: ["Build Distributable Assets"]
  #   types:
  #     - completed
  # workflow_call:
  #   inputs:
  #     workflow:
  #       description: "The workflow to run from a calling action"
  #       required: false
  #       type: string
  # workflow_call:
  #   inputs:
  #     workflow:
  #       description: "Tests to run (required)"
  #       required: true
  #       type: string
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"
        required: true
        type: string
      workflow:
        description: "Tests to run (required)"
        required: true
        type: choice
        options:
          - Release Tests
          - CI Tests
          - PR Tests
          - Atlas Tests
          - Bitcoin Tests
          - Epoch Tests
          - Slow Tests
          - Stacks-Blockchain Tests

run-name: ${{ inputs.workflow }}

jobs:
  create-cache:
    name: Create Test Cache
    # uses: wileyj/stacks-blockchain/.github/workflows/create_cache.yml@master
    uses: ./.github/workflows/create-cache.yml

  #####################################################
  stacks-blockchain-tests:
    if: |
      (
        inputs.workflow == 'Release Tests' ||
        inputs.workflow == 'CI Tests' ||
        inputs.workflow == 'Stacks-Blockchain Tests'
      )
    name: Stacks Blockchain Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/stacks-blockchain-tests.yml
    with:
      tag: ${{ inputs.tags }}

  bitcoin-tests:
    if: |
      (
        inputs.workflow == 'Release Tests' ||
        inputs.workflow == 'CI Tests' ||
        inputs.workflow == 'Bitcoin Tests'
      )
    name: Bitcoin Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/bitcoin-tests.yml
    with:
      tag: ${{ inputs.tags }}

  #####################################################
  atlas-tests:
    if: |
      (
        inputs.workflow == 'Release Tests' ||
        inputs.workflow == 'Atlas Tests' 
      )
    name: Atlas Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/atlas-tests.yml
    with:
      tag: ${{ inputs.tags }}

  epoch-tests:
    if: |
      (
        inputs.workflow == 'Release Tests' ||
        inputs.workflow == 'Epoch Tests'
      )
    name: Epoch Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/epoch-tests.yml
    with:
      tag: ${{ inputs.tags }}

  slow-tests:
    if: |
      (
        inputs.workflow == 'Release Tests' ||
        inputs.workflow == 'Slow Tests'
      )
    name: Slow Tests
    needs:
      - create-cache
    # uses: wileyj/stacks-blockchain/.github/workflows/build-source-binary.yml@master
    uses: ./.github/workflows/slow-tests.yml
    with:
      tag: ${{ inputs.tags }}
