## Github workflow to create multiarch binaries from source

name: Matrix Test

on:
  workflow_dispatch:

## change the display name to the tag being built
run-name: Matrix Test

jobs:
  ## Runs when the following is true:
  ##  - tag is provided
  ##  - workflow is building default branch (master)
  artifact:
    name: Matrix Test
    runs-on: ubuntu-latest
    strategy:
      ## Run a maximum of 10 builds concurrently, using the matrix defined in inputs.arch
      max-parallel: 10
      matrix:
        arch:
          - linux-musl
          - linux-glibc
          - macos 
          - windows
        # stdlib:
        #   - glibc
        #   - musl
        cpu:
          - arm64
          - armv7
          - x86-64
          - x86-64-v3
        exclude:
          - arch: windows # excludes windows-arm64
            cpu: arm64
          - arch: windows # excludes windows-armv7
            cpu: armv7
          - arch: macos # excludes macos-armv7
            cpu: armv7
          # - arch: macos # excludes macos-x86-64-v3
          #   cpu: x86-64-v3


    steps:
     ## Setup Docker for the builds
      - name: Docker setup
        run: |
          echo "docker setup"

      - name: set env
        run: |
          case ${cpu} in
              x86-64)
                  DOCKERFILE_CPU="x64"
                  ARCHIVE_NAME="x64"
                  ;;
              x86-64-v3)
                  DOCKERFILE_CPU="x64"
                  ARCHIVE_NAME="x64-v3"
                  ;;
              *)
                  DOCKERFILE_CPU="${{ matrix.cpu }}"
                  ARCHIVE_NAME="${{ matrix.cpu }}"
                  ;;
          esac
          echo "DOCKERFILE=Dockerfile.${{ matrix.arch }}-${DOCKERFILE_CPU}" >> "$GITHUB_ENV"
          echo "ARCHIVEFILE=${{ matrix.arch }}_${ARCHIVE_NAME}" >> "$GITHUB_ENV"

      ## Build the binaries using defined dockerfiles
      - name: Build Binary (${{ matrix.arch }}_${{ matrix.cpu }})
        id: build_binaries
        run: |
          echo "build binaries"
          echo "Buildfile: Dockerfile.${{ matrix.arch }}-${{ matrix.cpu }}"
          echo "dockerfile var: ${{ env.DOCKERFILE }}"
          echo "archivefile var: ${{ env.ARCHIVEFILE }}"
          echo "build args:"
          echo "
            STACKS_NODE_VERSION=${{ inputs.tag || env.GITHUB_SHA_SHORT }}
            OS_ARCH=${{ matrix.arch }}
            TARGET_CPU=${{ matrix.cpu }}
            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
          "

      ## Compress the binary artifact
      - name: Compress artifact
        id: compress_artifact
        run: |
          echo "zip --junk-paths ${{ env.ARCHIVE_NAME }} ./release/${{ matrix.arch }}/*"

      ## Upload the binary artifact to the github action (used in `github-release.yml` to create a release)
      - name: Upload artifact
        id: upload_artifact
        run: |
          echo "path: ${{ env.ARCHIVE_NAME }}.zip"
